### ISSUE TITLE
stability 

### ISSUE THREAD

**Issue by gabrielcsapo** [typicode/lowdb#118]
12.5 was a gold standard to `it just works` now with the latest 13.0 beta and up it is completely unusable. I don't understand the move to es6 and fanciness when this literally `just worked`. @typicode I appreciate your open source contributions, but I am going to have to switch to something else the latest beta left a bad taste in my mouth.

> Thanks for all the fish.

**Comment by typicode** [comment]
Hi @gabrielcsapo,

Thank you for the feedbacks. There were indeed a lot of [changes](https://github.com/typicode/lowdb/releases/tag/v0.13.0) in terms of API compared to previous releases.

About stability, were you impacted by the various beta releases? I tried to use [dist-tag](https://docs.npmjs.com/cli/dist-tag) so that people using `v0.12` should not have `v0.13.0-beta.x` installed automatically unless they specify that they want `v0.13.0-beta.x` in their `package.json`. Now lowdb `v0.13` is out of beta.

What don't you like in particular with `v0.13`? what doesn't `just work`?

**Comment by gabrielcsapo** [comment]
@typicode the introduction of es6 and babel alone bring this module's size up by a fair amount. The implementation has changed and with that the need to include lodash as a explicitly defined dependency.  I honestly thought `v0.12.5` was the best release and moving forward the focus would be one speed and efficiency instead of changing the interface.
