### ISSUE TITLE
Question: Does it rewrite the entire database to disk incase there is a change or a new item?

### ISSUE THREAD

**Issue by keevitaja** [typicode/lowdb#122]
Does it rewrite the entire database to disk incase there is a change or a new item?

Like can it be used with a simple, but slightly larger database too? About 100k entries

**Comment by typicode** [comment]
Hi @keevitaja,

Yes, since the storage is JSON, there's no simple way to update just one line in it without rewriting it.
I would say 100k items is still OK or if the database is not bigger than 10MB.

But in reality, it depends on different factors:

- What's the size of the database. For example, if you have 100k small items you may end up with ~1MB database which is fine, or if they are complex your database can be a lot bigger ~100MB which mean more time to write the entire database to disk.
- How often do you write to it.
- Is it for a local database (for example for an Electron app), a small website or for something that should support a lot of users, run multiple instance with a lot of concurrent write and critical data.

**Comment by keevitaja** [comment]
Thank you for responding!
