### ISSUE TITLE
Async Read

### ISSUE THREAD

**Issue by sebald** [typicode/lowdb#126]
Hi there,

this is more a request for clarification than a problem with `lowdb`, which is awesome btw ❤️ 

In the documentation you'll always find this sample code to read form the db:

```js
db.get('posts')
  .find({ id: 1 })
  .value()
```

But isn't this a **sync** read, even though I set `fileAsync` as `storage` option? Will this cause any issues when the db is queried a lot (e.g. reading old data)?

If so, how to do an async read?

**Comment by typicode** [comment]
Hi @sebald,

Thanks for the feedback. Sure, here's how it work:

```js
// synchronous read to load the database (happens once)
const db = low('db.json', { storage: fileAsync })

// query is done synchronously in memory
db.get('posts')
  .find({ id: 1 })
  .value()

// writing is asynchronous (uses fs.writeFile) and happens behind the scene
// steno handles that https://github.com/typicode/steno
db.get('posts')
  .push({ title: 'new post' })
  .value()
```

Read is synchronous. When the application starts, it usually doesn't matter if it's async or not.

Queries are done in memory, since the application is usually the only one to use the file, there's often no need to re-read from file every time.

Writing is the only async operation. It makes sense to use it, if you want to avoid blocking the main thread and look for perf (for CLI or local servers a few ms aren't noticed by the user).

You can force a re-read, though using `db.read()`.

If it doesn't suit your need, you can also create your own storage (see https://github.com/typicode/lowdb/blob/master/src/file-async.js and https://github.com/typicode/lowdb).

Here's a generic file reader with async read:

```js
const steno = require('steno')
const { stringify } = require('./json')

module.exports = {
  read: (src, deserialize = JSON.parse) => {
    return new Promise((resolve, reject) => {
      fs.readFile(src, (data, err) => {
        if (err) return reject(err)
        resolve(deserialize(data))
      })
    })
  },
  write: (dest, obj, serialize = stringify) => {
    return new Promise((resolve, reject) => {
      const data = serialize(obj)

      steno.writeFile(dest, data, (err) => {
        if (err) return reject(err)
        resolve()
      })
    })
  }
}
```

If you use this kind of storage, db need to be initialized this way then:

```js
low('db.json', { format: customFormat })
  .then((db) => ... )
```

Hope it clarifies things and let me know if you have any other question :)

**Comment by sebald** [comment]
Thanks for the thorough and quick reply. Guess my confusion also comes from when I had `writeOnChange` still (by default) set to `true`. When I started to write tests I would always "read" the old db state with the following implementation:

```js
function createModel (model) {
  models
    .push(createEntitiy(model))
    .value()
}

function getModel (id) {
  return getId(id)
    .cloneDeep()
    .value()
}
```

And the tests:

```js
const model = { id: 5, type: 'unicorn' }
dbService.createModel(model)
  .then(() => dbService.getModel(5)) // returns undefined
```

When I set `writeOnChange = true` and changed the write method(s) to:

```js
function createModel (model) {
  models
    .push(createEntitiy(model))
    .value()
  return db.write();
}
```

Everything worked as expected. But I thought that I also could read async 😃 
I'll read sync for now, because I really like how small and simple `lowdb` is and do not want to add custom stuff around it.

*Note: Just posted the above so if everyone else gets confused can re-read this.*

**Comment by typicode** [comment]
> Note: Just posted the above so if everyone else gets confused can re-read this.

Thanks for the explanation :)
