### ISSUE TITLE
Move the lodash peer dependency

### ISSUE THREAD

**Issue by Siilwyn** [typicode/lowdb#127]
I think `lodash` should be under the normal dependencies right? Without it installed `lowdb` doesn't work.

**Comment by typicode** [comment]
Hi @Siilwyn,

Initially it was to let people have more control on the version of `lodash` they use with `lowdb` (see also https://github.com/typicode/lowdb/issues/109).

The other reason was also to be able to build `dist/lowdb.js` without `lodash`, so that there's no need to rebuild `dist/lowdb.js` every time `lodash` is updated.

But after giving some more thoughts/research, there's other way to do all this. I've created a `next` branch where `lodash` is `dependency` again, it will be merged eventually.

Thank you for the feedback :+1:

**Comment by Siilwyn** [comment]
Thanks for taking your time to reply, sounds good!

**Comment by typicode** [comment]
Should be good in `v0.14.0`
https://github.com/typicode/lowdb/releases/tag/v0.14.0
