### ISSUE TITLE
What does .value() return for error or no records

### ISSUE THREAD

**Issue by dkebler** [typicode/lowdb#145]
I see you abandoned having .value() returning a promise.  That's fine I can wire that up myself since it's lazy processing.

I just need to understand what .value() returns in the two cases.

1.  error in find/filter query syntax or keys, or any other functions preceding .value()  ??  

2.  .value() returns no records.    "null" maybe ???

**Comment by dkebler** [comment]
Hmmm... found this repo https://github.com/jt-wang/jodb
which adds promises to underscore_db   but not lowdb

Now I'm confused about my options 

What is underscore_db to lowdb, should I be using it instead? 
Readme just says "Tip You can extend lowdb with underscore-db."  how?  why?

What is about this jodb?  It's already a year old.  Usable in your opinion?

**Basically what is your suggestion/recommendaton for "promisifying" queries.**

**Comment by typicode** [comment]
> I see you abandoned having .value() returning a promise. That's fine I can wire that up myself since it's lazy processing.

Yes, there were bugs with this approach.

> error in find/filter query syntax or keys, or any other functions preceding .value() ??

`.value()` works exactly the same way as in a lodash chain (i.e. `_({}).chain().someFunctions().value()`), so errors aren't catch.

For example, this will throw an error:

```js
_({}).get('a').get('b').value()
// Uncaught TypeError: Cannot read property 'get' of undefined(…)
```

For `find` it can return `undefined` and for filter `[]`.

> What is underscore-db to lowdb, should I be using it instead?

Underscore-db can be seen as a set of helpers that you can add to lowdb to make it easier to manipulate `id` based data.

For example, if you have:

```
{
  "posts": [ { "id": 1 }, { "id": 2 } ]
}
```

With lowdb, you can do:

```js
db.get('posts').find(post => post.id === id).value()
```

With lowdb + underscore-db, you can do:

```js
db.get('posts').getById(id).value()
```

As a rule of thumb, if your data has no `id` property, you don't need to add underscore-db.

To add underscore-db, you have an example [here](https://github.com/typicode/lowdb#how-to-use-id-based-resources)

> What about this repo jodb?

I've not tried these repos, so I can't tell, sorry.

> Basically what is your suggestion/recommendation for "promisifying" queries.

First question, do you really need to have asynchronous operations?
If you're building a CLI or very small server, it's usually easier to work with synchronous code.

If yes, then do you need to wait for them to complete?
Because you can add async storage and have lowdb save data for you in the "background". Just call `.value()` and it will be saved "at some point".

```js
low('db.json', { storage: require('lowdb/lib/file-async') })
```

However if you need to be sure that data has been written before continuing and want to use promises, you need to disable `writeOnChange` and use `.write()` which returns a promise in async mode:

```js
low('db.json', {
  storage: require('lowdb/lib/file-async'),
  writeOnChange: false
})

db.get('posts')
  .push({ title: 'foo' })
  .value()

db.write()
  .then(() => console.log('data has been written'))
```

**Comment by dkebler** [comment]
thx for all the clarifications.  appreciated.  closing this.
