### ISSUE TITLE
toJson? 

### ISSUE THREAD

**Issue by tony-gutierrez** [typicode/lowdb#150]
After doing a .get.value() I get an array of objects. However any manipulation of them is persisted. 

To avoid this I an currently cloning them, but is there not a better way to remove the linkage and persistence? I would like to do: object.toJSON() and then do my manipulations but that function is undefined.

**Comment by typicode** [comment]
Hi @tony-gutierrez,

Unfortunately no, because it's the same reference/instance. The only way to get a new one is to clone.

Even without lowdb, if you manipulate arrays in an object, they will get updated in the object if you change them outside.

```js
const o = { a: [] }
const b = o.a
b.push(1)
console.log(o) // { a: [ 1 ] }
``` 

That said, there are methods in lodash that doesn't mutate.

For example:

```js
db.get('posts').push({}).value() // will change posts
db.get('posts').concat({}).value() // won't change posts

db.get('posts').remove({ published: true }).value() // will change posts
db.get('posts').filter({ published: true }).value() // won't change posts
```

It's often mentioned in lodash docs if it mutates or not.

Also, in ES6 you have some syntactic sugar to clone an array:

```js
const a = [1, 2, 3]
const b = [...a] // new array

const newPosts = [...db.get('posts').value()]
```

Hope this helps.

**Comment by tony-gutierrez** [comment]
Thanks.
