### ISSUE TITLE
Question: high memory consumption when using file-sync storage

### ISSUE THREAD

**Issue by samuelstein** [typicode/lowdb#162]
I'm not sure if i understand the file-sync storage correctly. i want to use a ~140mb json file as database file. when i initialize the database as file storage it seems that the whole file will be loaded in memory.
i thought that this will only happen when i use the in memory storage option. is that true?

**Comment by typicode** [comment]
Hi @samuelstein,

That's correct but with JSON files, AFAIK, it's not possible to load them partially. Even without lowdb you would have the same issue:

```js
const fs = require('fs')
const data = fs.readFileSync('db.json') // will take 10mb in memory
```

The good point is that since everything is in memory, access to data and manipulation is fast.

As for in-memory storage, one of the use case can be for tests where you may want to switch storage:

```js
const storage = process.env.NODE === 'test'
  ? require('lowdb/lib/storages/memory')
  : require('lowdb/lib/storages/file-sync')

const db = low('db.json', { storage })

// could also be written like this
const db = process.env.NODE === 'test'
  ? low()
  : low('db.json')
```

Or if your data is volatile and you don't need to store it.

**Comment by samuelstein** [comment]
unfortunately you are right. thanks for clearifing.
