### ISSUE TITLE
When use lodash find function not match,the return all objects,but not undefined.

### ISSUE THREAD

**Issue by humbinal** [typicode/lowdb#163]
lodash find Returns the matched element, else undefined. [https://lodash.com/docs/4.17.4#find](https://lodash.com/docs/4.17.4#find)

my db.json:
```
{
  "posts": [
    { "user": "barney",  "age": 36, "active": true },
    { "user": "fred",    "age": 40, "active": false },
    { "user": "pebbles", "age": 1,  "active": true }
  ]
}
```

my code:
```
db.get('posts')
        .find({'id': 0})
        .write().then(x => res.send(x));
```

And I receiced all of this :
```
{
  "posts": [
    {
      "user": "barney",
      "age": 36,
      "active": true
    },
    {
      "user": "fred",
      "age": 40,
      "active": false
    },
    {
      "user": "pebbles",
      "age": 1,
      "active": true
    }
  ]
}
```

**Comment by typicode** [comment]
Hi @humbinal,

It's a bug with `write`, I'll fix it. Thank you for the report.

That said, you could simplify your code. In this case `write` is not necessary because `find` doesn't change your database and so there's no need to persist it.

```js
const post = db.get('posts')
  .find({ id: 0 })
  .value()

res.send(post)
```

`write` should be used when you make a change. For example with `set`, `unset`, `push`, etc... in lodash docs there's usually a mention when a method mutates the object or array.

**Comment by typicode** [comment]
It's fixed it on master. I need to do some refactoring but I will publish it on npm just after :)

**Comment by humbinal** [comment]
Thank's for your attention, but in lowdb examples,This used `write` ,so I also use this. [https://github.com/typicode/lowdb/tree/master/examples](https://github.com/typicode/lowdb/tree/master/examples)

**Comment by typicode** [comment]
My bad, thanks for the heads up, it's a mistake :) I'll update

**Comment by typicode** [comment]
Should be better in `v0.15.5`, examples have been updated too.
