### ISSUE TITLE
TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by rkamun1** [typicode/lowdb#211]
Hi, 

First of all, thank you for this fantastic project.

I am trying to use `lowdb` in a `create-react-app` and I get the error `TypeError: Cannot read property 'prototype' of undefined` this error shows up when I add the line `const FileSync = require('lowdb/adapters/FileSync')`, which throws an error at `var fs = require('graceful-fs');`. 

My stacktrace is pasted below. 

Thank you for your assistance.

```
patch
node_modules/graceful-fs/graceful-fs.js:166
  163 | }
  164 | 
  165 | var fs$ReadStream = fs.ReadStream
> 166 | ReadStream.prototype = Object.create(fs$ReadStream.prototype)
  167 | ReadStream.prototype.open = ReadStream$open
  168 | 
  169 | var fs$WriteStream = fs.WriteStream
```

```
(anonymous function)
node_modules/graceful-fs/graceful-fs.js:27
  24 |   })
  25 | }
  26 | 
> 27 | module.exports = patch(require('./fs.js'))
  28 | if (process.env.TEST_GRACEFUL_FS_GLOBAL_PATCH) {
  29 |   module.exports = patch(fs)
  30 | }
```

**Comment by typicode** [comment]
Hi @SirBertly,

Thank you :)

It's because `create-react-app` code run in the browser and `FileSync` adapter is meant to be used in a Node environment.

You can persist the data using `LocalStorage` adapter, but I don't think that's what you want to do. To write to file with `lowdb` you need to have a server to handle requests from your React app.

https://github.com/typicode/lowdb/tree/master/examples#server

**Comment by HongJheLi** [comment]
Same issue. 
Thanks.

**Comment by ForeveHG** [comment]
Thanks.
