### ISSUE TITLE
两次请求获取数据不一致

### ISSUE THREAD

**Issue by fay04** [typicode/lowdb#270]
本地请求ok,服务器上每次请求数据都跟前一次不一致

**Comment by fay04** [comment]
egg项目，koa没问题

**Comment by typicode** [comment]
For future reference, as far as I understand, it seems data is getting inconsistent when lowdb is running on a server but fine locally. Maybe if there's a cluster of servers or if the data is being re-read "while" being written, besides that I don't know.

But I guess since then a solution has probably been found, so I'm going to close it as suggested and I'm sorry for the delay.
