### ISSUE TITLE
Need maintainers? 😁

### ISSUE THREAD

**Issue by alvaropinot** [typicode/lowdb#273]
I'll be happy to help here and there with some PR reviewing and merging :)

Maybe anyone that's interested in this could add himself to this issue with a nice +1 or a brief description of what they can help with 😄

**Comment by craigplafferty** [comment]
+1

**Comment by sant123** [comment]
@typicode ?

**Comment by typicode** [comment]
Hey @alvaropinot,

Thanks a lot for offering help (and sorry for the delay).

Lowdb codebase is very small and most of the dependencies are quite stable, so in terms of code it doesn't require as much maintainance as other projects.

That said, there are often questions asked in issues that, unfortunately, I don't have the time to always answer.
That's one area where help is always welcome.

I've just started working on lowdb `v2`. There's a branch but it's still very much a WIP.

I'll list tasks so that people can help if they want. It'll probably be things like trying the new version, bug reports/fixes, proofreading docs ... so that it gets out of beta faster.

**Comment by typicode** [comment]
So I've created this https://github.com/typicode/lowdb/issues/302 🚀🙂
