### ISSUE TITLE
Next release ?

### ISSUE THREAD

**Issue by Stoakes** [typicode/lowdb#286]
Hi

Thank you for this project, which makes my data management in a small server much easier.

I'd like to know if you plan to have a release in the coming weeks ?
It's been almost one year since there haven't been one, so maybe a v1.0.1, with the updated dependencies could be a good thing.

**Comment by typicode** [comment]
Hi @Stoakes,

Thanks for the feedback :)

> I'd like to know if you plan to have a release in the coming weeks ?

No promises but hopefully. It'll be a v2 with, among other things, better TypeScript support.

> It's been almost one year since there haven't been one, so maybe a v1.0.1, with the updated dependencies could be a good thing.

Good point, I've just checked `dependencies` using `npm outdated` and they are up to date. So users should get the latest one.

As for `devDependencies`, that's true that they're a little outdated but since I'm working on `v2` I think I'll leave it like that.

**Comment by Stoakes** [comment]
Ok,

Thanks for your answer. Good luck for the v2.

**Comment by typicode** [comment]
> Good luck for the v2.

Thanks :)
