### ISSUE TITLE
Sorting existing database error

### ISSUE THREAD

**Issue by costagolub** [typicode/lowdb#35]
Have some problem with sorting object by key = "created_time" in the array, have been trying a lot of methods but nothing working for me 

This issue ticket didn't help me [link](https://github.com/typicode/lowdb/issues/15)

What I have
```javascript
var low = require('lowdb');
var db = low("./database/db.json");

db('dbname').push({object});
db('dbname').push({object});
db('dbname').push({object});
and more
```
After filled database I have this 
```javascript
{
 "dbname": [
  {
     "created_time": "..."
  },
  {
    ...
  },
 ...
} 
```
This is how I tried to sort object in array by "created_time" value 
```javascript
db.object.dbname = db('dbname').sortBy('created_time').value();
db.save();

or thus

db('dbname ').chain().sortBy('created_time').value();
db.save();
```
In both cases I get this error 
```javascript
..., [object Object],[object Object] has no method 'value'
```

**Comment by typicode** [comment]
Hi Constantine,

lowdb API has changed since the issue you referenced ([changelog](https://github.com/typicode/lowdb/releases)).

On __"one-method"__ calls you now don't need to explicitly call `.value()` anymore to get the value:

```javascript
db('dbname').push({a: 1}).value() // old syntax
db('dbname').push({a: 1})         // new syntax
```

If you want to chain method calls, you now must add `.chain()` __and__ `.value()` (`.value()` is needed because the chain won't be evaluated else). 

```javascript
db('dbname').chain().push({a: 1}).push({b: 2})          // will do nothing
db('dbname').chain().push({a: 1}).push({b: 2}).value()  // will create 2 entries
```

I hope this clarifies things a bit :)

Now regarding your issue, you should replace:

```javascript
db.object.dbname = db('dbname').sortBy('created_time').value()
```

By this:

```javascript
db.object.dbname = db('dbname').sortBy('created_time')
```

But your other example should work:

```javascript
db('dbname').chain().sortBy('created_time').value() // OK
```

So, I've tried to reproduce using the same structure:

```json
{
  "dbname": [
    {
      "created_time": "777"
    },
    {
      "created_time": "888"
    },
    {
      "created_time": "999"
    }
  ]
}
```

With this code:

```javascript
var low = require('./src')
var db = low('./db.json')

console.log(db('dbname').sortBy('created_time'))
console.log(db('dbname').chain().sortBy('created_time').value())

db.object.dbname = db('dbname').sortBy('created_time')
db.save()

db('dbname').chain().sortBy('created_time').value()
db.save()
```

But I don't have an error. Maybe check your lowdb version?

**Comment by costagolub** [comment]
Thanks for your answer and help, finally it works. it's great! 

I update lowdb and this line of code works fine 
````javascript
db.object.dbname= db('dbname').sortBy('created_time')
````
but this in my case doesn't make any interaction to the database
````javascript
db('dbname').chain().sortBy('created_time').value()
````

**Comment by typicode** [comment]
You're welcome and do not hesitate if you have other questions. Hope lowdb will help you in your project :)

Actually, It's because lowdb only wraps lodash methods and persists data when lodash changes the original array. 

So, if you have a look at `sortBy` [doc](https://lodash.com/docs#sortBy), it "Creates an array of elements, sorted in ascending order". That's why it's not saved. It's something to need to be aware.

But it's a good and bad thing. It's a good thing, because If you're sorting many times using many attributes in your app, you may not want to persist each time. And not such a good one, because it's kind of unexpected.

The current good way is to do like you did:

```javascript
db('dbname').object = // ...
db.save()
```

You can create mixins, if you need to add some custom methods to lowdb or you can have a look at projects like https://github.com/TheNodeILs/lodash-contrib to find in-place array sort.
