### ISSUE TITLE
"Uncaught SyntaxError: Unexpected end of input", source: http://localhost:4000/index.html (0)

### ISSUE THREAD

**Issue by kurdin** [typicode/lowdb#36]
If database file just empty and has no ``{}`` inside, the error happens: 

````console
"Uncaught SyntaxError: Unexpected end of input", source: http://localhost:4000/index.html (0)
````

**Comment by typicode** [comment]
Hi kurdin,

Thanks for the issue. It's a `JSON.parse` error because the JSON file is malformed.
I'm not sure what lowdb should do about it. 

```javascript
var low = require('lowdb')
low('db.json') // if db.json doesn't exist, it will be created with {} content
```

**Comment by kurdin** [comment]
You could try/catch error from JSON.parse and create warning string saying something like: ``JSON file db.json is malformed `` then check if that file is empty and if it is then return new empty object ``{} `` add to message string: ``and empty, creating new database db.json``.  Output string as Warning message. 
If file not empty, add to string:  ``and not empty, we could not use file db.json for database`` and throw Error with that message.

**Comment by typicode** [comment]
I agree, at least telling the user which file is malformed would be an enhancement.

**Comment by kurdin** [comment]
When you develop something with lowdb, easiest way to reset db is to delete content of db file or delete the file but then you need to open it again to see changes. So deleting content of the db file much quiker in development env.

**Comment by etiktin** [comment]
I agree with @kurdin. If the file is empty it's reasonable to assume that lowdb will handle it as an empty database the same way it does with a non existing file. The only reason it doesn't do it right now is because `JSON.parse` throws an exceptions on empty strings. This behavior of `JSON.parse` is somewhat controversial and some alternative implementations return null or undefined instead (that was the behavior of jQuery's `parseJSON` upto version 1.9).
PR #44 contains my suggestion for a solution which handles non-existing file, empty file and a file that contains only whitespace (e.g. the developer selected all content and clicked Enter/Return) the same way. The main change was in disk.read. We make sure that we return a trimmed string instead of `Buffer`, which means that if it's empty we won't try to parse it (exactly like we do with a non existing file). If parse still fails, it means that the database is actually corrupted so we throw an appropriate message (e.g. `The "db.json" database is corrupted (malformed JSON)`).

@typicode, please review and let us know what you think.

**Comment by typicode** [comment]
Thanks for the detailed explanation and the PR.
After giving some more thoughts, it makes sense. I'll merge it.

**Comment by typicode** [comment]
Released `v0.8.0` with this feature.

I've changed `the "db.json" database is corrupted (malformed JSON)` to  `Malformed JSON`.
Mainly because [steno](https://github.com/typicode/steno), which is used to write data to disk, should prevent file corruption.

**Comment by etiktin** [comment]
Thanks. The text change sounds fine.

**Comment by typicode** [comment]
You're welcome, thanks again for the PR.
Closing issue :)
