### ISSUE TITLE
Adapters for Mysql or Mongodb?

### ISSUE THREAD

**Issue by fritx** [typicode/lowdb#368]

**Comment by nicekiwi** [comment]
What's the use case for those over just using MongoDB and MySQL?

**Comment by fritx** [comment]
@nicekiwi for example, for seamless db-switching,
like I can switch between lowdb & mongodb by just change my adapter

**Comment by nicekiwi** [comment]
@fritx but the feature of MongoDB and LowDB are quite different and of SQL, I would suggest writing an adapter above lowDB to allow switching. In theory I could write an adapter for lowDB for MongoDB and SQL that would work.. though I still see little value in it as LowDB can't really take advantage of the power of either database.

**Comment by typicode** [comment]
In case anyone stumbles on this issue, I'd suggest using directly MySQL or MongoDB.

**Comment by ranjithrd** [comment]
My apologies if I'm necroposting, but could this not work with an offline/online model? Using LowDB as a middleman so that at the time of reading/writing, the adapter could dynamically resolve whether to send the data to a remote source and locally store it as JSON or localStorage or what not? Just an idea, I'd like to know if this is suited. Once again, sorry if I'm expecting a response on a closed issue
