### ISSUE TITLE
Can i use remote json database ?

### ISSUE THREAD

**Issue by MatteoGauthier** [typicode/lowdb#370]
I want to use https://jsonbox.io/ or https://jsonbin.io on my project, i love the syntax of lowdb what can i do ?

**Comment by kolarski** [comment]
You think you can write a simple Adapter - https://github.com/typicode/lowdb/blob/master/README.md#how-to-create-custom-adapters

**Comment by TehEbil** [comment]
Hi, I also have a similar question. We have a big database right now, about 200mb. We overwrote db.write() so it does do nothing, instead, we're calling the original db.write() function once every minute (else with every request by users, it resaves database and our server gets blocked for 3 seconds).

1) Do you have any other experience with saving data differently, like using json-stringify-safe or fast-safe-stringify? It seems that serialization takes most of the time to write the file.

2) Another Idea I have in mind is, I don't want my server to get blocked by fs. So, can I create an adapter which sends data to another node server, so he actually can save it, without losing any data (most importantly) ? I have seen an aws s3 adapter, but that actually means that we always have to send all data (200mb) to the s3 instance, right? So I thought maybe we could have a second server in the same local machine, so data can be copied internally instead of requesting it
