### ISSUE TITLE
Using remove({id: '1'}) instead of remove({id: 1})

### ISSUE THREAD

**Issue by ZeroZipZilch** [typicode/lowdb#396]
I just spent a good hour trying to figure out why my `.remove()` wasn't working when using the following code:

```js
db.get('quotes')
        .remove({ id: req.params.id })
        .write()
```

Where reg.params.id is a paramter from an express DELETE request.

In the end, I figured that the JSON actually contained an `int` rather than a `string`. Would it be possible to either make it not matter, or preferably make it log and error saying that the value "id" is not a string, or something along those lines? Thinking mainly for future developers.

The way I had to solve this was by using:

```js
db.get('quotes')
        .remove({ id: parseInt(req.params.id) })
        .write()
```

**Comment by angeal185** [comment]
That is a server side validation issue. You should be validating that data before it touches your db.
A basic  example:
```js
app.delete('/quotes/:id', function (req, res) {
  let id = parseInt(req.params.id);
  if(id){
    db.get('quotes').remove({id: id}).write();
    res.json({msg: 'item deleted'});
  } else {
    res.status(400).json({msg: 'invalid params'});
  }
})
```

there would be conflict issues for some if you made it so that .remove() could view strings as integers.
for example if someone had the following collection.

```js

[{
  id: 1
},{
  id: '1'
}]
```
These are not the same but would be viewed as being the same.
