### ISSUE TITLE
shortid is deprecated

### ISSUE THREAD

**Issue by tinjaw** [typicode/lowdb#430]
shortid is deprecated, because the architecture is unsafe. we instead recommend Nano ID, which has the advantage of also being significantly faster than shortid

from: https://github.com/dylang/shortid#shortid-is-deprecated-because-the-architecture-is-unsafe-we-instead-recommend-nano-id-which-has-the-advantage-of-also-being-significantly-faster-than-shortid

**Comment by typicode** [comment]
Thanks for the heads up

**Comment by carterbancroft** [comment]
@tinjaw can you provide any context on what "the architecture is unsafe" means? I'm trying to find some context on this because I would like to understand the level of risk around this package for systems that are already using it. Google is failing me though and I can't find any context except this ticket, the warning on NPM and the warning on GH (which is linked to by this ticket).

**Comment by haydenbbickerton** [comment]
@carterbancroft [this comment is the closest I've seen, can't vouch for it though](https://github.com/ai/nanoid/issues/8#issuecomment-321153379)
