### ISSUE TITLE
Can I use lowdb to store blockchain information on every node?

### ISSUE THREAD

**Issue by salemalem** [typicode/lowdb#479]
LowDB says it's only for small projects. Why can't I scale up to infinity? Is it convenient for storing blockchain information on every node synchronously?

**Comment by typicode** [comment]
It's because it's limited to one Node instance. You can't have multiple Node instances write to the same target.
Also, the whole database is loaded in memory and is serialized before write. It's fine for small size but let's say you have 1GB of data, it'll be slower.

I don't know for the blockchain. In any case, I'd suggest trying it and experimenting to see if lowdb fits your need.

https://github.com/typicode/lowdb#limits
