### ISSUE TITLE
Failed to compile [ This dependency was not found ] v2.1.0

### ISSUE THREAD

**Issue by 233Bazinga** [typicode/lowdb#491]
![Snipaste_2021-07-18_16-25-35](https://user-images.githubusercontent.com/52889695/126060831-1d6603e4-73c1-4cde-8aab-71ae96e8bda1.png)

**Comment by typicode** [comment]
Have you tried re-running `npm install`? Beside that, I don't see what could be done on lowdb side.

**Comment by felipeleivav** [comment]
@233Bazinga I had the same problem and fixed it by importing like this:

`import { Low, JSONFile } from 'lowdb/lib';`

I saw that here: https://github.com/typicode/lowdb/issues/462#issuecomment-849451452

**Comment by hungdev** [comment]
> @233Bazinga I had the same problem and fixed it by importing like this:
> 
> `import { Low, JSONFile } from 'lowdb/lib';`
> 
> I saw that here: [#462 (comment)](https://github.com/typicode/lowdb/issues/462#issuecomment-849451452)

I still get the error, can you give me full example?
Here is my code:
```
import { Low, Memory } from 'lowdb/lib';
import lodash from 'lodash';

const adapter = new Memory();

const db = new Low(adapter);

// Set default data
db.data ||= { posts: ['hello world', 'xyz'] }
db.write().then(() => {
  // Note: db.data needs to be initialized before lodash.chain is called.
  db.chain = lodash.chain(db.data);
  document.getElementById("app").innerHTML = db.data?.posts.map((post) => `<h1>${post}</h1>`);
});
```

**Comment by Youdaman** [comment]
I also had the same error in a Vue project:
```
This dependency was not found:

* lowdb in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save lowdb
```

The fix for me was to import the modules separately, so instead of:
```
import { LowSync, LocalStorage } from 'lowdb'
```
I instead used:
```
import { LowSync } from 'lowdb/lib/LowSync'
import { LocalStorage } from 'lowdb/lib/adapters/LocalStorage'
```
And things worked.

> Have you tried re-running `npm install`? Beside that, I don't see what could be done on lowdb side.

I deleted my node_modules and did a fresh install with yarn and still got the same error until I changed my imports.

Given that I'm getting this error in a Vue project my only guess is that it's related to babel/core-js/webpack or some config that needs tweaking.

So it's probably not an error on the lowdb side but maybe a "fix" is to update the docs with a note about the separate imports (unless it's there already and I've missed it).

**Comment by andyesfly** [comment]
I changed my imports,but I got a new error : 

This dependency was not found:

* steno in ./node_modules/lowdb/lib/adapters/TextFile.js

To install it, you can run: npm install --save steno
