### ISSUE TITLE
How to disable json beautifier when changed DB

### ISSUE THREAD

**Issue by quangnv13** [typicode/lowdb#543]
Now lowdb alway beautifier json file. But i want it's minifier for best perfomance.
<img width="751" alt="image" src="https://user-images.githubusercontent.com/64973827/183601883-e22afb60-dbab-4d92-afa2-b313b10b6d68.png">

<img width="822" alt="image" src="https://user-images.githubusercontent.com/64973827/183602186-754dd702-a828-43f7-adcb-3c9067db8397.png">

How i can do that?

ps: My DB can have 100000 record and may be have 1000000 lines in json file.

**Comment by arctome** [comment]
Well, I have the same question. 
Due to JSONFile adapter has a default `JSON.stringify` format (https://github.com/typicode/lowdb/blob/fdf004fdbe98b5e809ac2033c78d74252fe1bc48/src/adapters/JSONFile.ts#L21), maybe you need to create a minified version of JSONFile adapter.

PS: the adapter in JSONFile is declared as "private" member, so extends the JSONFile class may be not a chance to resolve this need.

**Comment by typicode** [comment]
I'd recommend creating a new adapter. You can check existing ones, they're pretty simple.
Here's an example for your case:

```ts
import { Adapter } from 'lowdb'
import { TextFile } from 'lowdb/node'

class JSONFileMin<T> implements Adapter<T> {
  #adapter: TextFile

  constructor(filename: string) {
    this.#adapter = new TextFile(filename)
  }

  async read(): Promise<T | null> {
    const data = await this.#adapter.read()
    if (data === null) {
      return null
    } else {
      return JSON.parse(data) as T
    }
  }

  write(obj: T): Promise<void> {
    return this.#adapter.write(JSON.stringify(obj)) // <- minified JSON
  }
}
```
