### ISSUE TITLE
Why Json File is pretty

### ISSUE THREAD

**Issue by MM25Zamanian** [typicode/lowdb#574]
Why don't you minify the json files?

**Comment by jamiller619** [comment]
- JSON is, by definition, [_human readable_ text to store and transmit data](https://en.wikipedia.org/wiki/JSON). Minified JSON is basically the complete opposite of that.
- You can easily create an adapter to store JSON minified! It's literally the same code as `JSONFile.ts`. Just make a copy of that file and name it `JSONMinified.ts` (or whatever you want to call it) with a single change on line 21:
```ts
write(obj: T): Promise<void> {
  return this.#adapter.write(JSON.stringify(obj, null, 2))
}
``` 
to:
```ts
write(obj: T): Promise<void> {
  return this.#adapter.write(JSON.stringify(obj))
}
```
and boom, minified JSON. 

I'm only chiming in here because I recently went through the same thought process, however, ended up coming back around, full-circle lol, in favor of using the default, pretty JSON. The space savings were not significant and if I'm truly going for a small file size, then JSON is probably a bad choice to begin with. CSV, and even traditional SQL databases, would be much better option IMO.
