### ISSUE TITLE
Does the database stay in memory?

### ISSUE THREAD

**Issue by johnRivs** [typicode/lowdb#73]
If I read the database in `file1.js`:
```js
var users = require('lowdb')('./db.json')('users');

// do something with users
```
Does the package perform a second file read operation when I use it in `file2.js`:
```js
var settings = require('lowdb')('./db.json')('settings');

// do something with settings
```
Or does it get read once after `node index.js` and it stays in memory?

**Comment by typicode** [comment]
Hi @johnRivs 

Every time you call `low('db.json')` it will read the database and create another database object in memory.

For example:

```js
var low = require('lowdb')
var users = low('db.json')('users')
var settings = low('db.json')('settings')

users.push({ name: 'foo' })
settings.push({ param: 'foo' })
```

Your `db.json` will contain only `users` or `settings`:

```json
{
  "users": [
    { "name": "foo" }
  ]
}
```

```json
{
  "settings": [
    { "param": "foo" }
  ]
}
```

Because you have 2 different instances of lowdb working concurrently on the same file.
So, when you call `low('db.json')` you need to store it somewhere or pass it to subsequent modules.

A simple approach could be:

```js
// db.js

// This will be executed only once
module.exports = require('lowdb')('db.json')
```

```js
// file1.js
var users = require('./db')('users')
```

```js
// file2.js
var settings = require('./db')('settings')
```

**Comment by johnRivs** [comment]
Gotcha. I've been doing something like that.
