### ISSUE TITLE
Any experience with Heroku apps?

### ISSUE THREAD

**Issue by s-a** [typicode/lowdb#88]
Any time my app re spawns in Heroku the db.json is in it s initial state again. Seems it works in memory only but when I test this local on my machine lowdb writes every modification down to the db.json file in filesystem. Any suggestions how I can fix this?

**Comment by typicode** [comment]
Unfortunately, you can't persist files on Heroku. You need to use add-ons for that and store in a database like MongoDB, Postgres, ... or things like S3.

So, apps using lowdb and deployed on Heroku are usually read-only apps.

But since lowdb `v0.12`, you can now set custom storage. So it should theorically be possible to tell lowdb to store database in something different than a file. However, as far as I know, it hasn't been done yet.

**Comment by s-a** [comment]
Thnx for your help!

**Comment by ackmanx** [comment]
For future curious people, here's a Heroku help article explaining why this is the case: https://help.heroku.com/K1PPS2WM/why-are-my-file-uploads-missing-deleted
